#!/bin/bash

ID=$$
W=$(tput cols)
H=$(tput lines)

if [ "$1" = '--nopv' ]; then
    IMG=0
    shift
elif [ "$W" -gt 52 ] || [ "$H" -gt 13 ]; then
    IMG=1
    COLS=$(tput cols)
    LINS=$(tput lines)
    PV=(--preview-window)
    if [ "$W" -gt $((H*3)) ] || [ "$W" -gt 169 ]; then
        PV+=(right:50%)
        X=$((COLS / 2 + 2))
        Y=1
        W=$((((COLS - 1) / 2) - 2))
        H=$((LINS - 2))
    else
        PV+=(down:50%)
        X=1
        Y=$((LINS / 2 + 2))
        W=$((COLS - 2))
        H=$((((LINS - 1) / 2) - 2))
    fi
    PV+=(--preview "stpv {} $H $W $X $Y $ID")
fi

if [ "$IMG" = 1 ]; then
    stpvimg --listen $ID 2>/dev/null &
fi

fzf "${PV[@]}" --reverse "$@"

if [ "$IMG" = 1 ]; then
    stpvimg --end $ID || true
fi
